### ISSUE TITLE
updating packages

### ISSUE THREAD

**Issue by tkanos** [syedabuthahirm/react-materialui-boilerplate#1]
Hello @syedabuthahirm ,

I like your boilerplate, so in order to make it more usable I am : 
- upgrading the packages
- updating the code
- ejecting from create-script

for now I have already done the 2 first (upgrade + update)

are you interested in it, before I eject ?

**Comment by syedabuthahirm** [comment]
Thanks for the Pull request @tkanos. 
Eject has no backward option so ejecting maybe not suitable for all the cases. so, we don't have to eject the project by default.
